# Generated by Django 5.0.6 on 2024-10-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профіль користувача', 'verbose_name_plural': 'Профіля користувачів'},
        ),
        migrations.AddField(
            model_name='profile',
            name='is_worker',
            field=models.BooleanField(default=False),
        ),
    ]
